module.exports = {
  'Cookies': require('./Cookies'),
  'Colors': require('./Colors'),
  'Dates': require('./Dates'),
  'Fns': require('./Fns'),
  'Lists': require('./Lists'),
  'Maps': require('./Maps'),
  'Objs': require('./Objs'),
  'Strings': require('./Strings'),
  'Urls': require('./Urls'),
  'Compression': require('./Compression'),
  'Encrypt': require('./Encrypt'),
  'Nets': require('./Nets'),
  'Documents': require('./Documents'),
  'Other': require('./Other'),
};
